export const PLANS = {
  starter: {
    name: 'Starter',
    price_inr: 9999,
    setup_fee_inr: 4999,
    founding_price_inr: 6999,
    features: [
      'Up to 50 employees',
      '50 rights requests/year',
      '1 DPO assignment',
      'AI privacy notice generator',
      'Basic DPDP training (5 modules)',
      'RoPA management',
      'Breach tracker',
    ],
    max_requests: 50,
    max_dpos: 1,
  },
  growth: {
    name: 'Growth',
    price_inr: 24999,
    setup_fee_inr: 9999,
    founding_price_inr: 17999,
    features: [
      'Up to 200 employees',
      '250 rights requests/year',
      '3 DPO assignments',
      'Full AI tools suite',
      'Custom training sessions',
      'Consent management',
      'Advanced RoPA',
    ],
    max_requests: 250,
    max_dpos: 3,
  },
  business: {
    name: 'Business',
    price_inr: 59999,
    setup_fee_inr: 19999,
    founding_price_inr: 41999,
    features: [
      'Up to 1000 employees',
      'Unlimited rights requests',
      '10 DPO assignments',
      'DPIA assistance',
      'Breach notification drafting',
      'Audit-ready reporting',
      'Priority support',
    ],
    max_requests: -1,
    max_dpos: 10,
  },
  enterprise: {
    name: 'Enterprise',
    price_inr: null,
    setup_fee_inr: null,
    founding_price_inr: null,
    features: [
      'Unlimited employees',
      'Unlimited everything',
      'Dedicated DPO',
      'SLA guarantee',
      'Custom integrations',
      'Onsite training',
    ],
    max_requests: -1,
    max_dpos: -1,
  },
} as const

export type PlanKey = keyof typeof PLANS
